### PR TITLE
Ai branch

### PR DESCRIPTION
**Pull request by docDock**
AI now has pathfinding and basic path following ability. Path following does not work well enough currently to navigate through doors consistently.

### CODE REVIEW

**Comment by docDock** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by starwolfy** [comment]
recheck

**Comment by starwolfy** [comment]
recheck

**Comment by starwolfy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by docDock** [comment]
all changes that were made to code outside of artificial_unintelligence are related to changing the HumanMalePawnBundle::spawn() function to make it work with the new ai type.

**Review by starwolfy — APPROVED** [review]
This looks good. I can also see that Cargo.toml, LICENSE and README.md have been updated to more recent versions I have released of them, which is fine too.

**Pull request merged**
